### ISSUE TITLE
Error:(39, 13) Attribute instrumentation#android.test.InstrumentationTestRunner@label value=(Tests for com.example.android.interpolatorplayground) from AndroidManifest.xml:39:13

### ISSUE THREAD

**Issue by sphairo** [googlesamples/android-Interpolator#1]
Error:(38, 13) Attribute instrumentation#android.test.InstrumentationTestRunner@targetPackage value=(com.example.android.interpolatorplayground) from AndroidManifest.xml:38:13

**Comment by thagikura** [comment]
Same for the comment in the CardView, 

We'll address the issue anytime soon, thanks.

**Comment by thagikura** [comment]
Fixed by c9fb88d3dae8e95b252a9cf11e51513841315d11
