### ISSUE TITLE
Cannot resolve symbol com.example.android.interpolatorplayground

### ISSUE THREAD

**Issue by sphairo** [googlesamples/android-Interpolator#2]
Error:(38, 13) Attribute instrumentation#android.test.InstrumentationTestRunner@targetPackage value=(com.example.android.interpolatorplayground) from AndroidManifest.xml:38:13

**Comment by thagikura** [comment]
Same for the comment in the CardView sample,

We'll address the issue anytime soon, thanks.

**Comment by codingjeremy** [comment]
This issue has been migrated to the new animations repo: [github.com/android/animation](https://github.com/android/animation).
