### ISSUE TITLE
Error:(37, 9) Attribute instrumentation#android.test.InstrumentationTestRunner@label value=(Tests for CardView sample) from AndroidManifest.xml:37:9

### ISSUE THREAD

**Issue by sphairo** [googlesamples/android-Interpolator#3]
Error:(38, 13) Attribute instrumentation#android.test.InstrumentationTestRunner@targetPackage value=(com.example.android.interpolatorplayground) from AndroidManifest.xml:38:13

Cannot resolve symbol android:targetPackage="com.example.android.interpolatorplayground"

**Comment by thagikura** [comment]
Same for the comment in the CardView,

We'll address the issue anytime soon, thanks.

**Comment by codingjeremy** [comment]
This issue has been migrated to the new animations repo: [github.com/android/animation](https://github.com/android/animation).
