### ISSUE TITLE
Application screenshots in Readme

### ISSUE THREAD

**Issue by metc** [googlesamples/android-Interpolator#4]
Hi,

Since commit a001031c33499dcd1e883560a25b99c881442fa8, the two application screenshots are not displayed correctly in the [README](https://github.com/googlesamples/android-Interpolator/blob/master/README.md) file.

**Comment by keyboardsurfer** [comment]
Internal: 26808632

**Comment by metc** [comment]
Ping @keyboardsurfer

**Comment by codingjeremy** [comment]
This issue has been migrated to the new animations repo: [github.com/android/animation](https://github.com/android/animation).
